on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: make file
        run: |
          echo "foobar" >> .env
      - name: read file
        run: |
          cat .env
      - name: set env
        run: |
          echo "GREETING=Hello" >> $GITHUB_ENV
      - name: use env
        run: |
          echo "${{ env.GREETING }} World!"

