on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GREETING: fi
    steps:
      - name: make file
        run: |
          echo "foobar" >> .env
      - name: read file
        run: |
          cat .env
      - name: use env
        run: |
          echo "$LOCALIZED_GREETING"
        env:
          LOCALIZED_GREETING: ${{ (contains(env.GREETING, 'f') && "Moi") || (contains(env.GREETING, 'en') && "Hello") }}
